production: &production
  host: http://habriki.com
  hostname: habriki.com
  email: info@habriki.com

development: &development
  <<: *production
  host: http://habriki.local
  hostname: habriki.local

test:
  <<: *development
  host: http://habriki.test
  hostname: habriki.test
