production: &production
  host: http://www.habriki.com
  host_name: www.habriki.com
  email: info@habriki.com

development: &development
  <<: *production
  host: http://www.habriki.local
  host_name: www.habriki.local

test:
  <<: *development
